// Deck for Taboo, in English and Italian. Each card: a guess word plus 5 forbidden ("taboo") words.
// Index-aligned between languages: WORDS.en[i] and WORDS.it[i] are the same concept.
const WORDS = {
  en: [
    { word: "PIZZA", taboo: ["Italian", "Cheese", "Slice", "Pepperoni", "Delivery"] },
    { word: "BASKETBALL", taboo: ["Hoop", "Dribble", "NBA", "Court", "Ball"] },
    { word: "BIRTHDAY", taboo: ["Cake", "Candles", "Party", "Age", "Gift"] },
    { word: "SMARTPHONE", taboo: ["Call", "Apple", "Screen", "App", "Text"] },
    { word: "OCEAN", taboo: ["Water", "Fish", "Blue", "Wave", "Beach"] },
    { word: "TEACHER", taboo: ["School", "Student", "Class", "Lesson", "Grade"] },
    { word: "SNOWMAN", taboo: ["Snow", "Carrot", "Winter", "Frosty", "Melt"] },
    { word: "GUITAR", taboo: ["String", "Music", "Play", "Rock", "Chord"] },
    { word: "HOSPITAL", taboo: ["Doctor", "Nurse", "Sick", "Patient", "Emergency"] },
    { word: "COFFEE", taboo: ["Caffeine", "Cup", "Morning", "Bean", "Starbucks"] },
    { word: "ASTRONAUT", taboo: ["Space", "Rocket", "Moon", "NASA", "Suit"] },
    { word: "LIBRARY", taboo: ["Book", "Quiet", "Read", "Shelf", "Borrow"] },
    { word: "VOLCANO", taboo: ["Lava", "Erupt", "Mountain", "Ash", "Hot"] },
    { word: "WEDDING", taboo: ["Bride", "Groom", "Ring", "Marry", "Dress"] },
    { word: "DINOSAUR", taboo: ["Extinct", "Fossil", "Rex", "Jurassic", "Bone"] },
    { word: "UMBRELLA", taboo: ["Rain", "Open", "Wet", "Cover", "Handle"] },
    { word: "SUPERHERO", taboo: ["Cape", "Powers", "Villain", "Mask", "Save"] },
    { word: "TOOTHBRUSH", taboo: ["Teeth", "Brush", "Paste", "Clean", "Mouth"] },
    { word: "CAMPING", taboo: ["Tent", "Fire", "Outdoors", "Sleep", "Forest"] },
    { word: "PIRATE", taboo: ["Ship", "Treasure", "Ocean", "Parrot", "Sword"] },
    { word: "ALARM CLOCK", taboo: ["Wake", "Time", "Ring", "Snooze", "Morning"] },
    { word: "ROLLER COASTER", taboo: ["Ride", "Fast", "Loop", "Amusement", "Track"] },
    { word: "SANDWICH", taboo: ["Bread", "Lunch", "Slice", "Filling", "Sub"] },
    { word: "FIREWORKS", taboo: ["Sky", "Explode", "Bang", "Celebrate", "Fourth"] },
    { word: "YOGA", taboo: ["Stretch", "Mat", "Pose", "Breathe", "Calm"] },
    { word: "TAXI", taboo: ["Cab", "Driver", "Ride", "Yellow", "Fare"] },
    { word: "PENGUIN", taboo: ["Ice", "Bird", "Waddle", "Antarctica", "Black"] },
    { word: "MAGICIAN", taboo: ["Trick", "Wand", "Hat", "Rabbit", "Illusion"] },
    { word: "EARTHQUAKE", taboo: ["Shake", "Ground", "Tremor", "Richter", "Fault"] },
    { word: "SCARECROW", taboo: ["Field", "Crow", "Farm", "Straw", "Bird"] },
    { word: "SOCCER", taboo: ["Ball", "Goal", "Kick", "Field", "Team"] },
    { word: "CHRISTMAS", taboo: ["Santa", "Tree", "Gift", "Snow", "December"] },
    { word: "ROBOT", taboo: ["Machine", "Metal", "Circuit", "AI", "Battery"] },
    { word: "ZOO", taboo: ["Animal", "Cage", "Lion", "Ticket", "Visit"] },
    { word: "BEACH", taboo: ["Sand", "Sun", "Wave", "Towel", "Ocean"] },
    { word: "AIRPLANE", taboo: ["Fly", "Wing", "Pilot", "Sky", "Ticket"] },
    { word: "VAMPIRE", taboo: ["Blood", "Fangs", "Bat", "Night", "Garlic"] },
    { word: "DOCTOR", taboo: ["Hospital", "Sick", "Nurse", "Medicine", "Patient"] },
    { word: "BICYCLE", taboo: ["Wheel", "Pedal", "Ride", "Chain", "Helmet"] },
    { word: "SPIDER", taboo: ["Web", "Legs", "Insect", "Bite", "Crawl"] },
    { word: "RAINBOW", taboo: ["Colors", "Rain", "Sky", "Arc", "Sun"] },
    { word: "CASTLE", taboo: ["King", "Queen", "Tower", "Moat", "Knight"] },
    { word: "ICE CREAM", taboo: ["Cone", "Cold", "Scoop", "Flavor", "Melt"] },
    { word: "FARMER", taboo: ["Farm", "Crop", "Field", "Tractor", "Cow"] },
    { word: "TELEVISION", taboo: ["Screen", "Watch", "Remote", "Channel", "Show"] },
    { word: "MOUNTAIN", taboo: ["Climb", "Peak", "Snow", "High", "Hike"] },
    { word: "CLOWN", taboo: ["Circus", "Funny", "Nose", "Balloon", "Joke"] },
    { word: "TRAIN", taboo: ["Track", "Station", "Ride", "Wheels", "Conductor"] },
    { word: "NEWSPAPER", taboo: ["Print", "News", "Read", "Paper", "Article"] },
    { word: "KITCHEN", taboo: ["Cook", "Stove", "Food", "Sink", "Recipe"] },
    { word: "SPACESHIP", taboo: ["Rocket", "Space", "Alien", "Launch", "Astronaut"] },
    { word: "WATERFALL", taboo: ["Water", "Fall", "River", "Cliff", "Splash"] },
    { word: "GLASSES", taboo: ["Eyes", "See", "Lens", "Vision", "Wear"] },
    { word: "SKELETON", taboo: ["Bones", "Halloween", "Skull", "X-ray", "Body"] },
    { word: "FISHERMAN", taboo: ["Fish", "Hook", "Boat", "Rod", "Lake"] },
    { word: "ELEVATOR", taboo: ["Floor", "Button", "Up", "Down", "Building"] },
    { word: "BASEBALL", taboo: ["Bat", "Pitch", "Glove", "Home Run", "Field"] },
    { word: "GARDEN", taboo: ["Plant", "Flower", "Soil", "Grow", "Water"] },
    { word: "THUNDERSTORM", taboo: ["Lightning", "Rain", "Loud", "Cloud", "Sky"] },
    { word: "ARTIST", taboo: ["Paint", "Canvas", "Brush", "Draw", "Gallery"] },
  ],
  it: [
    { word: "PIZZA", taboo: ["Italiana", "Formaggio", "Fetta", "Forno", "Napoli"] },
    { word: "PALLACANESTRO", taboo: ["Canestro", "Palla", "NBA", "Campo", "Palleggiare"] },
    { word: "COMPLEANNO", taboo: ["Torta", "Candeline", "Festa", "Età", "Regalo"] },
    { word: "SMARTPHONE", taboo: ["Chiamata", "Apple", "Schermo", "App", "Messaggio"] },
    { word: "OCEANO", taboo: ["Acqua", "Pesce", "Blu", "Onda", "Spiaggia"] },
    { word: "INSEGNANTE", taboo: ["Scuola", "Studente", "Classe", "Lezione", "Voto"] },
    { word: "PUPAZZO DI NEVE", taboo: ["Neve", "Carota", "Inverno", "Freddo", "Sciogliere"] },
    { word: "CHITARRA", taboo: ["Corda", "Musica", "Suonare", "Rock", "Accordo"] },
    { word: "OSPEDALE", taboo: ["Medico", "Infermiere", "Malato", "Paziente", "Emergenza"] },
    { word: "CAFFÈ", taboo: ["Caffeina", "Tazza", "Mattina", "Chicco", "Espresso"] },
    { word: "ASTRONAUTA", taboo: ["Spazio", "Razzo", "Luna", "NASA", "Tuta"] },
    { word: "BIBLIOTECA", taboo: ["Libro", "Silenzio", "Leggere", "Scaffale", "Prestito"] },
    { word: "VULCANO", taboo: ["Lava", "Eruzione", "Montagna", "Cenere", "Caldo"] },
    { word: "MATRIMONIO", taboo: ["Sposa", "Sposo", "Anello", "Sposare", "Abito"] },
    { word: "DINOSAURO", taboo: ["Estinto", "Fossile", "Rex", "Giurassico", "Osso"] },
    { word: "OMBRELLO", taboo: ["Pioggia", "Aprire", "Bagnato", "Coprire", "Manico"] },
    { word: "SUPEREROE", taboo: ["Mantello", "Poteri", "Cattivo", "Maschera", "Salvare"] },
    { word: "SPAZZOLINO", taboo: ["Denti", "Spazzolare", "Dentifricio", "Pulire", "Bocca"] },
    { word: "CAMPEGGIO", taboo: ["Tenda", "Fuoco", "Natura", "Dormire", "Foresta"] },
    { word: "PIRATA", taboo: ["Nave", "Tesoro", "Mare", "Pappagallo", "Spada"] },
    { word: "SVEGLIA", taboo: ["Svegliarsi", "Ora", "Suonare", "Posticipare", "Mattina"] },
    { word: "MONTAGNE RUSSE", taboo: ["Giro", "Veloce", "Loop", "Luna Park", "Binario"] },
    { word: "PANINO", taboo: ["Pane", "Pranzo", "Fetta", "Farcito", "Salame"] },
    { word: "FUOCHI D'ARTIFICIO", taboo: ["Cielo", "Esplodere", "Botto", "Festeggiare", "Capodanno"] },
    { word: "YOGA", taboo: ["Stiramento", "Tappetino", "Posizione", "Respirare", "Calma"] },
    { word: "TAXI", taboo: ["Autista", "Corsa", "Giallo", "Tariffa", "Macchina"] },
    { word: "PINGUINO", taboo: ["Ghiaccio", "Uccello", "Dondolare", "Antartide", "Nero"] },
    { word: "MAGO", taboo: ["Trucco", "Bacchetta", "Cappello", "Coniglio", "Illusione"] },
    { word: "TERREMOTO", taboo: ["Scuotere", "Terra", "Scossa", "Richter", "Faglia"] },
    { word: "SPAVENTAPASSERI", taboo: ["Campo", "Corvo", "Fattoria", "Paglia", "Uccello"] },
    { word: "CALCIO", taboo: ["Palla", "Gol", "Calciare", "Campo", "Squadra"] },
    { word: "NATALE", taboo: ["Babbo Natale", "Albero", "Regalo", "Neve", "Dicembre"] },
    { word: "ROBOT", taboo: ["Macchina", "Metallo", "Circuito", "Intelligenza", "Batteria"] },
    { word: "ZOO", taboo: ["Animale", "Gabbia", "Leone", "Biglietto", "Visita"] },
    { word: "SPIAGGIA", taboo: ["Sabbia", "Sole", "Onda", "Asciugamano", "Mare"] },
    { word: "AEREO", taboo: ["Volare", "Ala", "Pilota", "Cielo", "Biglietto"] },
    { word: "VAMPIRO", taboo: ["Sangue", "Zanne", "Pipistrello", "Notte", "Aglio"] },
    { word: "DOTTORE", taboo: ["Ospedale", "Malato", "Infermiere", "Medicina", "Paziente"] },
    { word: "BICICLETTA", taboo: ["Ruota", "Pedale", "Pedalare", "Catena", "Casco"] },
    { word: "RAGNO", taboo: ["Ragnatela", "Zampe", "Insetto", "Mordere", "Strisciare"] },
    { word: "ARCOBALENO", taboo: ["Colori", "Pioggia", "Cielo", "Arco", "Sole"] },
    { word: "CASTELLO", taboo: ["Re", "Regina", "Torre", "Fossato", "Cavaliere"] },
    { word: "GELATO", taboo: ["Cono", "Freddo", "Pallina", "Gusto", "Sciogliere"] },
    { word: "CONTADINO", taboo: ["Fattoria", "Raccolto", "Campo", "Trattore", "Mucca"] },
    { word: "TELEVISIONE", taboo: ["Schermo", "Guardare", "Telecomando", "Canale", "Programma"] },
    { word: "MONTAGNA", taboo: ["Scalare", "Cima", "Neve", "Alto", "Escursione"] },
    { word: "PAGLIACCIO", taboo: ["Circo", "Divertente", "Naso", "Palloncino", "Scherzo"] },
    { word: "TRENO", taboo: ["Binario", "Stazione", "Viaggio", "Ruote", "Macchinista"] },
    { word: "GIORNALE", taboo: ["Stampa", "Notizie", "Leggere", "Carta", "Articolo"] },
    { word: "CUCINA", taboo: ["Cucinare", "Fornello", "Cibo", "Lavandino", "Ricetta"] },
    { word: "ASTRONAVE", taboo: ["Razzo", "Spazio", "Alieno", "Lancio", "Astronauta"] },
    { word: "CASCATA", taboo: ["Acqua", "Cadere", "Fiume", "Scogliera", "Spruzzo"] },
    { word: "OCCHIALI", taboo: ["Occhi", "Vedere", "Lente", "Vista", "Indossare"] },
    { word: "SCHELETRO", taboo: ["Ossa", "Halloween", "Teschio", "Radiografia", "Corpo"] },
    { word: "PESCATORE", taboo: ["Pesce", "Amo", "Barca", "Canna", "Lago"] },
    { word: "ASCENSORE", taboo: ["Piano", "Pulsante", "Su", "Giù", "Edificio"] },
    { word: "BASEBALL", taboo: ["Mazza", "Lancio", "Guantone", "Fuoricampo", "Campo"] },
    { word: "GIARDINO", taboo: ["Pianta", "Fiore", "Terra", "Crescere", "Annaffiare"] },
    { word: "TEMPORALE", taboo: ["Fulmine", "Pioggia", "Rumoroso", "Nuvola", "Cielo"] },
    { word: "ARTISTA", taboo: ["Dipingere", "Tela", "Pennello", "Disegnare", "Galleria"] },
  ],
};
