// Deck for Taboo, in English and Italian. Each card: a guess word, a category key,
// and 8 forbidden ("taboo") words. Index-aligned between languages: WORDS.en[i] and
// WORDS.it[i] are the same concept.

const CATEGORIES = ["food", "sports", "occasions", "objects", "nature", "people", "places", "animals", "fantasy", "activities", "famous"];

const CATEGORY_LABELS = {
  en: {
    food: "Food",
    sports: "Sports",
    occasions: "Occasions",
    objects: "Objects",
    nature: "Nature",
    people: "People & Jobs",
    places: "Places",
    animals: "Animals",
    fantasy: "Fantasy",
    activities: "Activities",
    famous: "Famous People",
  },
  it: {
    food: "Cibo",
    sports: "Sport",
    occasions: "Occasioni",
    objects: "Oggetti",
    nature: "Natura",
    people: "Persone e Mestieri",
    places: "Luoghi",
    animals: "Animali",
    fantasy: "Fantasia",
    activities: "Attività",
    famous: "Personaggi Famosi",
  },
};

const WORDS = {
  en: [
    { word: "PIZZA", category: "food", taboo: ["Italian", "Cheese", "Slice", "Pepperoni", "Delivery", "Oven", "Pizzeria", "Dough"] },
    { word: "BASKETBALL", category: "sports", taboo: ["Hoop", "Dribble", "NBA", "Court", "Ball", "Jump", "Team", "Shoot"] },
    { word: "BIRTHDAY", category: "occasions", taboo: ["Cake", "Candles", "Party", "Age", "Gift", "Balloon", "Wish", "Celebrate"] },
    { word: "SMARTPHONE", category: "objects", taboo: ["Call", "Apple", "Screen", "App", "Text", "Battery", "Camera", "Charger"] },
    { word: "OCEAN", category: "nature", taboo: ["Water", "Fish", "Blue", "Wave", "Beach", "Deep", "Salt", "Current"] },
    { word: "TEACHER", category: "people", taboo: ["School", "Student", "Class", "Lesson", "Grade", "Chalk", "Homework", "Classroom"] },
    { word: "SNOWMAN", category: "nature", taboo: ["Snow", "Carrot", "Winter", "Frosty", "Melt", "Cold", "Build", "Scarf"] },
    { word: "GUITAR", category: "objects", taboo: ["String", "Music", "Play", "Rock", "Chord", "Pick", "Strum", "Acoustic"] },
    { word: "HOSPITAL", category: "places", taboo: ["Doctor", "Nurse", "Sick", "Patient", "Emergency", "Bed", "Surgery", "Ambulance"] },
    { word: "COFFEE", category: "food", taboo: ["Caffeine", "Cup", "Morning", "Bean", "Starbucks", "Hot", "Espresso", "Mug"] },
    { word: "ASTRONAUT", category: "people", taboo: ["Space", "Rocket", "Moon", "NASA", "Suit", "Gravity", "Helmet", "Orbit"] },
    { word: "LIBRARY", category: "places", taboo: ["Book", "Quiet", "Read", "Shelf", "Borrow", "Librarian", "Card", "Study"] },
    { word: "VOLCANO", category: "nature", taboo: ["Lava", "Erupt", "Mountain", "Ash", "Hot", "Magma", "Crater", "Smoke"] },
    { word: "WEDDING", category: "occasions", taboo: ["Bride", "Groom", "Ring", "Marry", "Dress", "Vows", "Church", "Cake"] },
    { word: "DINOSAUR", category: "animals", taboo: ["Extinct", "Fossil", "Rex", "Jurassic", "Bone", "Giant", "Prehistoric", "Roar"] },
    { word: "UMBRELLA", category: "objects", taboo: ["Rain", "Open", "Wet", "Cover", "Handle", "Storm", "Fold", "Shade"] },
    { word: "SUPERHERO", category: "fantasy", taboo: ["Cape", "Powers", "Villain", "Mask", "Save", "Comic", "Hero", "Fly"] },
    { word: "TOOTHBRUSH", category: "objects", taboo: ["Teeth", "Brush", "Paste", "Clean", "Mouth", "Bristle", "Dentist", "Morning"] },
    { word: "CAMPING", category: "activities", taboo: ["Tent", "Fire", "Outdoors", "Sleep", "Forest", "Backpack", "Marshmallow", "Hiking"] },
    { word: "PIRATE", category: "fantasy", taboo: ["Ship", "Treasure", "Ocean", "Parrot", "Sword", "Flag", "Captain", "Island"] },
    { word: "ALARM CLOCK", category: "objects", taboo: ["Wake", "Time", "Ring", "Snooze", "Morning", "Bed", "Buzzer", "Set"] },
    { word: "ROLLER COASTER", category: "activities", taboo: ["Ride", "Fast", "Loop", "Amusement", "Track", "Scream", "Park", "Drop"] },
    { word: "SANDWICH", category: "food", taboo: ["Bread", "Lunch", "Slice", "Filling", "Sub", "Cheese", "Toast", "Wrap"] },
    { word: "FIREWORKS", category: "occasions", taboo: ["Sky", "Explode", "Bang", "Celebrate", "Fourth", "Colorful", "Show", "Rocket"] },
    { word: "YOGA", category: "activities", taboo: ["Stretch", "Mat", "Pose", "Breathe", "Calm", "Balance", "Studio", "Flexible"] },
    { word: "TAXI", category: "objects", taboo: ["Cab", "Driver", "Ride", "Yellow", "Fare", "Meter", "Street", "Hail"] },
    { word: "PENGUIN", category: "animals", taboo: ["Ice", "Bird", "Waddle", "Antarctica", "Black", "White", "Flightless", "Cold"] },
    { word: "MAGICIAN", category: "fantasy", taboo: ["Trick", "Wand", "Hat", "Rabbit", "Illusion", "Stage", "Show", "Vanish"] },
    { word: "EARTHQUAKE", category: "nature", taboo: ["Shake", "Ground", "Tremor", "Richter", "Fault", "Quake", "Rumble", "Crack"] },
    { word: "SCARECROW", category: "fantasy", taboo: ["Field", "Crow", "Farm", "Straw", "Bird", "Pole", "Hat", "Guard"] },
    { word: "SOCCER", category: "sports", taboo: ["Ball", "Goal", "Kick", "Field", "Team", "Referee", "Cleats", "World Cup"] },
    { word: "CHRISTMAS", category: "occasions", taboo: ["Santa", "Tree", "Gift", "Snow", "December", "Reindeer", "Stocking", "Holiday"] },
    { word: "ROBOT", category: "fantasy", taboo: ["Machine", "Metal", "Circuit", "AI", "Battery", "Wires", "Mechanical", "Beep"] },
    { word: "ZOO", category: "places", taboo: ["Animal", "Cage", "Lion", "Ticket", "Visit", "Exhibit", "Keeper", "Enclosure"] },
    { word: "BEACH", category: "nature", taboo: ["Sand", "Sun", "Wave", "Towel", "Ocean", "Shell", "Swim", "Umbrella"] },
    { word: "AIRPLANE", category: "objects", taboo: ["Fly", "Wing", "Pilot", "Sky", "Ticket", "Runway", "Passenger", "Airport"] },
    { word: "VAMPIRE", category: "fantasy", taboo: ["Blood", "Fangs", "Bat", "Night", "Garlic", "Coffin", "Bite", "Dracula"] },
    { word: "DOCTOR", category: "people", taboo: ["Hospital", "Sick", "Nurse", "Medicine", "Patient", "Stethoscope", "Clinic", "Checkup"] },
    { word: "BICYCLE", category: "objects", taboo: ["Wheel", "Pedal", "Ride", "Chain", "Helmet", "Handlebar", "Spokes", "Gear"] },
    { word: "SPIDER", category: "animals", taboo: ["Web", "Legs", "Insect", "Bite", "Crawl", "Eight", "Arachnid", "Spin"] },
    { word: "RAINBOW", category: "nature", taboo: ["Colors", "Rain", "Sky", "Arc", "Sun", "Prism", "Stripe", "Pot of Gold"] },
    { word: "CASTLE", category: "places", taboo: ["King", "Queen", "Tower", "Moat", "Knight", "Wall", "Drawbridge", "Throne"] },
    { word: "ICE CREAM", category: "food", taboo: ["Cone", "Cold", "Scoop", "Flavor", "Melt", "Sundae", "Vanilla", "Sprinkles"] },
    { word: "FARMER", category: "people", taboo: ["Farm", "Crop", "Field", "Tractor", "Cow", "Harvest", "Barn", "Plow"] },
    { word: "TELEVISION", category: "objects", taboo: ["Screen", "Watch", "Remote", "Channel", "Show", "Volume", "Broadcast", "Living Room"] },
    { word: "MOUNTAIN", category: "nature", taboo: ["Climb", "Peak", "Snow", "High", "Hike", "Summit", "Rocky", "Range"] },
    { word: "CLOWN", category: "people", taboo: ["Circus", "Funny", "Nose", "Balloon", "Joke", "Makeup", "Juggle", "Wig"] },
    { word: "TRAIN", category: "objects", taboo: ["Track", "Station", "Ride", "Wheels", "Conductor", "Rail", "Whistle", "Cargo"] },
    { word: "NEWSPAPER", category: "objects", taboo: ["Print", "News", "Read", "Paper", "Article", "Headline", "Journalist", "Daily"] },
    { word: "KITCHEN", category: "places", taboo: ["Cook", "Stove", "Food", "Sink", "Recipe", "Oven", "Fridge", "Counter"] },
    { word: "SPACESHIP", category: "fantasy", taboo: ["Rocket", "Space", "Alien", "Launch", "Astronaut", "Orbit", "Galaxy", "Fuel"] },
    { word: "WATERFALL", category: "nature", taboo: ["Water", "Fall", "River", "Cliff", "Splash", "Stream", "Mist", "Roar"] },
    { word: "GLASSES", category: "objects", taboo: ["Eyes", "See", "Lens", "Vision", "Wear", "Frame", "Blurry", "Prescription"] },
    { word: "SKELETON", category: "fantasy", taboo: ["Bones", "Halloween", "Skull", "X-ray", "Body", "Rattle", "Spine", "Rib"] },
    { word: "FISHERMAN", category: "people", taboo: ["Fish", "Hook", "Boat", "Rod", "Lake", "Bait", "Net", "Catch"] },
    { word: "ELEVATOR", category: "objects", taboo: ["Floor", "Button", "Up", "Down", "Building", "Lift", "Cable", "Doors"] },
    { word: "BASEBALL", category: "sports", taboo: ["Bat", "Pitch", "Glove", "Home Run", "Field", "Diamond", "Inning", "Umpire"] },
    { word: "GARDEN", category: "places", taboo: ["Plant", "Flower", "Soil", "Grow", "Water", "Seed", "Weed", "Hose"] },
    { word: "THUNDERSTORM", category: "nature", taboo: ["Lightning", "Rain", "Loud", "Cloud", "Sky", "Boom", "Flash", "Storm"] },
    { word: "ARTIST", category: "people", taboo: ["Paint", "Canvas", "Brush", "Draw", "Gallery", "Sketch", "Studio", "Creative"] },
    { word: "ALBERT EINSTEIN", category: "famous", taboo: ["Physicist", "Genius", "Relativity", "Germany", "Hair", "Formula", "Scientist", "Nobel"] },
    { word: "WILLIAM SHAKESPEARE", category: "famous", taboo: ["Playwright", "Hamlet", "England", "Sonnets", "Theatre", "Quill", "Stratford", "Romeo"] },
    { word: "LEONARDO DA VINCI", category: "famous", taboo: ["Painter", "Mona Lisa", "Inventor", "Renaissance", "Italy", "Sketch", "Genius", "Flying Machine"] },
    { word: "CHARLIE CHAPLIN", category: "famous", taboo: ["Actor", "Silent Film", "Comedian", "Mustache", "Cane", "Hat", "Tramp", "Black and White"] },
    { word: "CLEOPATRA", category: "famous", taboo: ["Egypt", "Queen", "Pharaoh", "Pyramid", "Nile", "Ancient", "Crown", "Asp"] },
    { word: "MICHAEL JORDAN", category: "famous", taboo: ["Basketball", "NBA", "Chicago", "Jump", "Number 23", "Dunk", "Bulls", "Shoes"] },
    { word: "MARILYN MONROE", category: "famous", taboo: ["Actress", "Blonde", "Hollywood", "Icon", "1950s", "Dress", "Star", "Glamour"] },
    { word: "BEETHOVEN", category: "famous", taboo: ["Composer", "Deaf", "Symphony", "Piano", "Germany", "Ninth", "Classical", "Orchestra"] },
  ],
  it: [
    { word: "PIZZA", category: "food", taboo: ["Italiana", "Formaggio", "Fetta", "Forno", "Napoli", "Impasto", "Pizzeria", "Pomodoro"] },
    { word: "PALLACANESTRO", category: "sports", taboo: ["Canestro", "Palla", "NBA", "Campo", "Palleggiare", "Squadra", "Tiro", "Salto"] },
    { word: "COMPLEANNO", category: "occasions", taboo: ["Torta", "Candeline", "Festa", "Età", "Regalo", "Palloncino", "Augurio", "Festeggiare"] },
    { word: "SMARTPHONE", category: "objects", taboo: ["Chiamata", "Apple", "Schermo", "App", "Messaggio", "Batteria", "Fotocamera", "Caricabatterie"] },
    { word: "OCEANO", category: "nature", taboo: ["Acqua", "Pesce", "Blu", "Onda", "Spiaggia", "Profondo", "Sale", "Corrente"] },
    { word: "INSEGNANTE", category: "people", taboo: ["Scuola", "Studente", "Classe", "Lezione", "Voto", "Gesso", "Compiti", "Aula"] },
    { word: "PUPAZZO DI NEVE", category: "nature", taboo: ["Neve", "Carota", "Inverno", "Freddo", "Sciogliere", "Costruire", "Sciarpa", "Palla di Neve"] },
    { word: "CHITARRA", category: "objects", taboo: ["Corda", "Musica", "Suonare", "Rock", "Accordo", "Plettro", "Acustica", "Nota"] },
    { word: "OSPEDALE", category: "places", taboo: ["Medico", "Infermiere", "Malato", "Paziente", "Emergenza", "Letto", "Chirurgia", "Ambulanza"] },
    { word: "CAFFÈ", category: "food", taboo: ["Caffeina", "Tazza", "Mattina", "Chicco", "Espresso", "Caldo", "Tazzina", "Bar"] },
    { word: "ASTRONAUTA", category: "people", taboo: ["Spazio", "Razzo", "Luna", "NASA", "Tuta", "Gravità", "Casco", "Orbita"] },
    { word: "BIBLIOTECA", category: "places", taboo: ["Libro", "Silenzio", "Leggere", "Scaffale", "Prestito", "Bibliotecario", "Tessera", "Studiare"] },
    { word: "VULCANO", category: "nature", taboo: ["Lava", "Eruzione", "Montagna", "Cenere", "Caldo", "Magma", "Cratere", "Fumo"] },
    { word: "MATRIMONIO", category: "occasions", taboo: ["Sposa", "Sposo", "Anello", "Sposare", "Abito", "Promesse", "Chiesa", "Torta"] },
    { word: "DINOSAURO", category: "animals", taboo: ["Estinto", "Fossile", "Rex", "Giurassico", "Osso", "Gigante", "Preistorico", "Ruggito"] },
    { word: "OMBRELLO", category: "objects", taboo: ["Pioggia", "Aprire", "Bagnato", "Coprire", "Manico", "Temporale", "Chiudere", "Riparo"] },
    { word: "SUPEREROE", category: "fantasy", taboo: ["Mantello", "Poteri", "Cattivo", "Maschera", "Salvare", "Fumetto", "Eroe", "Volare"] },
    { word: "SPAZZOLINO", category: "objects", taboo: ["Denti", "Spazzolare", "Dentifricio", "Pulire", "Bocca", "Setole", "Dentista", "Mattina"] },
    { word: "CAMPEGGIO", category: "activities", taboo: ["Tenda", "Fuoco", "Natura", "Dormire", "Foresta", "Zaino", "Marshmallow", "Escursione"] },
    { word: "PIRATA", category: "fantasy", taboo: ["Nave", "Tesoro", "Mare", "Pappagallo", "Spada", "Bandiera", "Capitano", "Isola"] },
    { word: "SVEGLIA", category: "objects", taboo: ["Svegliarsi", "Ora", "Suonare", "Posticipare", "Mattina", "Letto", "Allarme", "Impostare"] },
    { word: "MONTAGNE RUSSE", category: "activities", taboo: ["Giro", "Veloce", "Loop", "Luna Park", "Binario", "Urlare", "Parco", "Discesa"] },
    { word: "PANINO", category: "food", taboo: ["Pane", "Pranzo", "Fetta", "Farcito", "Salame", "Formaggio", "Tostato", "Involtino"] },
    { word: "FUOCHI D'ARTIFICIO", category: "occasions", taboo: ["Cielo", "Esplodere", "Botto", "Festeggiare", "Capodanno", "Colorato", "Spettacolo", "Razzo"] },
    { word: "YOGA", category: "activities", taboo: ["Stiramento", "Tappetino", "Posizione", "Respirare", "Calma", "Equilibrio", "Studio", "Flessibile"] },
    { word: "TAXI", category: "objects", taboo: ["Autista", "Corsa", "Giallo", "Tariffa", "Macchina", "Contatore", "Strada", "Chiamare"] },
    { word: "PINGUINO", category: "animals", taboo: ["Ghiaccio", "Uccello", "Dondolare", "Antartide", "Nero", "Bianco", "Non Vola", "Freddo"] },
    { word: "MAGO", category: "fantasy", taboo: ["Trucco", "Bacchetta", "Cappello", "Coniglio", "Illusione", "Palco", "Spettacolo", "Sparire"] },
    { word: "TERREMOTO", category: "nature", taboo: ["Scuotere", "Terra", "Scossa", "Richter", "Faglia", "Sisma", "Rombo", "Crepa"] },
    { word: "SPAVENTAPASSERI", category: "fantasy", taboo: ["Campo", "Corvo", "Fattoria", "Paglia", "Uccello", "Palo", "Cappello", "Guardia"] },
    { word: "CALCIO", category: "sports", taboo: ["Palla", "Gol", "Calciare", "Campo", "Squadra", "Arbitro", "Scarpini", "Mondiale"] },
    { word: "NATALE", category: "occasions", taboo: ["Babbo Natale", "Albero", "Regalo", "Neve", "Dicembre", "Renna", "Calza", "Festività"] },
    { word: "ROBOT", category: "fantasy", taboo: ["Macchina", "Metallo", "Circuito", "Intelligenza", "Batteria", "Fili", "Meccanico", "Bip"] },
    { word: "ZOO", category: "places", taboo: ["Animale", "Gabbia", "Leone", "Biglietto", "Visita", "Recinto", "Custode", "Esposizione"] },
    { word: "SPIAGGIA", category: "nature", taboo: ["Sabbia", "Sole", "Onda", "Asciugamano", "Mare", "Conchiglia", "Nuotare", "Ombrellone"] },
    { word: "AEREO", category: "objects", taboo: ["Volare", "Ala", "Pilota", "Cielo", "Biglietto", "Pista", "Passeggero", "Aeroporto"] },
    { word: "VAMPIRO", category: "fantasy", taboo: ["Sangue", "Zanne", "Pipistrello", "Notte", "Aglio", "Bara", "Mordere", "Dracula"] },
    { word: "DOTTORE", category: "people", taboo: ["Ospedale", "Malato", "Infermiere", "Medicina", "Paziente", "Stetoscopio", "Clinica", "Visita"] },
    { word: "BICICLETTA", category: "objects", taboo: ["Ruota", "Pedale", "Pedalare", "Catena", "Casco", "Manubrio", "Raggi", "Marcia"] },
    { word: "RAGNO", category: "animals", taboo: ["Ragnatela", "Zampe", "Insetto", "Mordere", "Strisciare", "Otto", "Aracnide", "Filare"] },
    { word: "ARCOBALENO", category: "nature", taboo: ["Colori", "Pioggia", "Cielo", "Arco", "Sole", "Prisma", "Striscia", "Pentola d'Oro"] },
    { word: "CASTELLO", category: "places", taboo: ["Re", "Regina", "Torre", "Fossato", "Cavaliere", "Muro", "Ponte Levatoio", "Trono"] },
    { word: "GELATO", category: "food", taboo: ["Cono", "Freddo", "Pallina", "Gusto", "Sciogliere", "Coppa", "Vaniglia", "Codette"] },
    { word: "CONTADINO", category: "people", taboo: ["Fattoria", "Raccolto", "Campo", "Trattore", "Mucca", "Raccolta", "Fienile", "Aratro"] },
    { word: "TELEVISIONE", category: "objects", taboo: ["Schermo", "Guardare", "Telecomando", "Canale", "Programma", "Volume", "Trasmissione", "Salotto"] },
    { word: "MONTAGNA", category: "nature", taboo: ["Scalare", "Cima", "Neve", "Alto", "Escursione", "Vetta", "Roccioso", "Catena"] },
    { word: "PAGLIACCIO", category: "people", taboo: ["Circo", "Divertente", "Naso", "Palloncino", "Scherzo", "Trucco", "Giocoleria", "Parrucca"] },
    { word: "TRENO", category: "objects", taboo: ["Binario", "Stazione", "Viaggio", "Ruote", "Macchinista", "Rotaia", "Fischio", "Merci"] },
    { word: "GIORNALE", category: "objects", taboo: ["Stampa", "Notizie", "Leggere", "Carta", "Articolo", "Titolo", "Giornalista", "Quotidiano"] },
    { word: "CUCINA", category: "places", taboo: ["Cucinare", "Fornello", "Cibo", "Lavandino", "Ricetta", "Forno", "Frigorifero", "Bancone"] },
    { word: "ASTRONAVE", category: "fantasy", taboo: ["Razzo", "Spazio", "Alieno", "Lancio", "Astronauta", "Orbita", "Galassia", "Carburante"] },
    { word: "CASCATA", category: "nature", taboo: ["Acqua", "Cadere", "Fiume", "Scogliera", "Spruzzo", "Ruscello", "Nebbia", "Rombo"] },
    { word: "OCCHIALI", category: "objects", taboo: ["Occhi", "Vedere", "Lente", "Vista", "Indossare", "Montatura", "Sfocato", "Prescrizione"] },
    { word: "SCHELETRO", category: "fantasy", taboo: ["Ossa", "Halloween", "Teschio", "Radiografia", "Corpo", "Costole", "Colonna", "Tremare"] },
    { word: "PESCATORE", category: "people", taboo: ["Pesce", "Amo", "Barca", "Canna", "Lago", "Esca", "Rete", "Catturare"] },
    { word: "ASCENSORE", category: "objects", taboo: ["Piano", "Pulsante", "Su", "Giù", "Edificio", "Cabina", "Cavo", "Porte"] },
    { word: "BASEBALL", category: "sports", taboo: ["Mazza", "Lancio", "Guantone", "Fuoricampo", "Campo", "Diamante", "Inning", "Arbitro"] },
    { word: "GIARDINO", category: "places", taboo: ["Pianta", "Fiore", "Terra", "Crescere", "Annaffiare", "Seme", "Erbaccia", "Tubo"] },
    { word: "TEMPORALE", category: "nature", taboo: ["Fulmine", "Pioggia", "Rumoroso", "Nuvola", "Cielo", "Boato", "Lampo", "Tempesta"] },
    { word: "ARTISTA", category: "people", taboo: ["Dipingere", "Tela", "Pennello", "Disegnare", "Galleria", "Schizzo", "Studio", "Creativo"] },
    { word: "ALBERT EINSTEIN", category: "famous", taboo: ["Fisico", "Genio", "Relatività", "Germania", "Capelli", "Formula", "Scienziato", "Nobel"] },
    { word: "WILLIAM SHAKESPEARE", category: "famous", taboo: ["Drammaturgo", "Amleto", "Inghilterra", "Sonetti", "Teatro", "Penna d'Oca", "Stratford", "Romeo"] },
    { word: "LEONARDO DA VINCI", category: "famous", taboo: ["Pittore", "Gioconda", "Inventore", "Rinascimento", "Italia", "Schizzo", "Genio", "Macchina Volante"] },
    { word: "CHARLIE CHAPLIN", category: "famous", taboo: ["Attore", "Cinema Muto", "Comico", "Baffi", "Bastone", "Cappello", "Vagabondo", "Bianco e Nero"] },
    { word: "CLEOPATRA", category: "famous", taboo: ["Egitto", "Regina", "Faraone", "Piramide", "Nilo", "Antico", "Corona", "Aspide"] },
    { word: "MICHAEL JORDAN", category: "famous", taboo: ["Basket", "NBA", "Chicago", "Salto", "Numero 23", "Schiacciata", "Bulls", "Scarpe"] },
    { word: "MARILYN MONROE", category: "famous", taboo: ["Attrice", "Bionda", "Hollywood", "Icona", "Anni Cinquanta", "Abito", "Star", "Fascino"] },
    { word: "BEETHOVEN", category: "famous", taboo: ["Compositore", "Sordo", "Sinfonia", "Pianoforte", "Germania", "Nona", "Classica", "Orchestra"] },
  ],
};
